import { MigrationInterface, QueryRunner, Table, TableIndex } from 'typeorm';

// ─────────────────────────────────────────────────────────────────────────────
//  Migration: 1700000000000-CreateMonitorSnapshots
//
//  Creates the monitor_snapshots table with:
//   • varchar(36) primary key – UUID generated by TypeORM in app code
//   • created_at datetime (MySQL has no "timestamp with time zone" type)
//   • Aggregated host / problem counters per sync cycle
//
//  MySQL compatibility notes:
//   • uuid type → varchar(36)   (MySQL has no native UUID column type)
//   • No DEFAULT UUID() on id   (MySQL forbids function-call defaults; TypeORM
//                                 generates the UUID in application code before
//                                 every INSERT via generationStrategy: 'uuid')
//   • "timestamp with time zone" → datetime  (MySQL stores UTC natively)
//   • CURRENT_TIMESTAMP is the only function MySQL allows as a column default
// ─────────────────────────────────────────────────────────────────────────────

export class CreateMonitorSnapshots1700000000000 implements MigrationInterface {
  public readonly name = 'CreateMonitorSnapshots1700000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'monitor_snapshots',
        columns: [
          {
            // varchar(36) holds the canonical 8-4-4-4-12 UUID string.
            // No database DEFAULT – TypeORM generates the UUID in app code
            // before every INSERT (generationStrategy: 'uuid'), so MySQL
            // never needs to call a function itself.
            name:               'id',
            type:               'varchar',
            length:             '36',
            isPrimary:          true,
            isGenerated:        true,
            generationStrategy: 'uuid',
          },
          {
            // MySQL does not support "timestamp with time zone".
            // datetime stores values in UTC when the session tz is UTC (default).
            name:       'created_at',
            type:       'datetime',
            isNullable: false,
            default:    'CURRENT_TIMESTAMP',
          },
          {
            name:       'total_hosts',
            type:       'int',
            isNullable: false,
          },
          {
            name:       'online',
            type:       'int',
            isNullable: false,
          },
          {
            name:       'offline',
            type:       'int',
            isNullable: false,
          },
          {
            name:       'critical',
            type:       'int',
            isNullable: false,
          },
          {
            name:       'warning',
            type:       'int',
            isNullable: false,
          },
        ],
      }),
      true, // ifNotExists = true – safe to re-run
    );

    await queryRunner.createIndex(
      'monitor_snapshots',
      new TableIndex({
        name:        'IDX_monitor_snapshots_created_at',
        columnNames: ['created_at'],
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropIndex(
      'monitor_snapshots',
      'IDX_monitor_snapshots_created_at',
    );
    await queryRunner.dropTable('monitor_snapshots');
  }
}

